// 
// Code auto-generated by Ray.
// Sat Apr 25 10:42:52 EDT 2026
//
package mitch.plugin;
import charlie.card.Card;
import charlie.shoe.Shoe01;
public class MyFixBugShoe1 extends Shoe01 {
    @Override
    public void init() {
        cards.clear();
        // Game T0 {5}: You A+A+J+J | Dealer 7+K >> Win{5}
        // Round 1
        // You
        cards.add(new Card(Card.ACE, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(7, Card.Suit.CLUBS));
        // Round 2
        // You
        cards.add(new Card(Card.ACE, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(Card.KING, Card.Suit.DIAMONDS));
        // You
        // Hitting
        cards.add(new Card(Card.JACK, Card.Suit.SPADES));
        cards.add(new Card(Card.JACK, Card.Suit.SPADES));
    }
}
// END generated code