// 
// Code auto-generated by Ray.
// Sun May 03 13:52:42 EDT 2026
// 
package mitch.plugin;
import charlie.card.Card;
import charlie.shoe.Shoe01;
public class MyFixBugShoe2 extends Shoe01 {
    @Override
    public void init() {
        cards.clear();
        // Game T0 {5}: You 10+10+A+A | Dealer 10+6 >> Win{5}
        // Round 1
        // You
        cards.add(new Card(10, Card.Suit.HEARTS));
        // Dealer
        cards.add(new Card(10, Card.Suit.DIAMONDS));
        // Round 2
        // You
        cards.add(new Card(10, Card.Suit.DIAMONDS));
        // Dealer
        cards.add(new Card(6, Card.Suit.CLUBS));
        // You
        // Hitting
        cards.add(new Card(Card.ACE, Card.Suit.SPADES));
        cards.add(new Card(Card.ACE, Card.Suit.CLUBS));
    }
}
// END generated code